clients:
  alman-partners:
    vault_path: clients/alman-partners
    emails:
      - almanpartners.com.au
    contacts:
      - paul@alman.com.au
  capital-partners:
    vault_path: clients/capital-partners
    emails:
      - capital-partners.com.au
    contacts:
      - clamprecht@capital-partners.com.au
  regency-invests:
    vault_path: clients/regency-invests
    emails:
      - regencyinvests.com
    contacts: []
  bkfi:
    vault_path: client/bkfi
    emails:
      - brooklynfi.com
    contacts:
      - john@brooklynfi.com
      - aj@brooklynfi.com
      - shane@brooklynfi.com
  spp:
    vault_path: clients/spp
    emails:
      - spcfo.com
    contacts:
      - shaun.erickson@spcfo.com
      - rene.jarquin@spcfo.com
  north-road:
    vault_path: clients/north-road
    emails:
      - northroadic.com
    contacts:
      - marshall.mcalister@northroadic.com
industry:
  liyria:
    vault_path: industry/liyria
    emails:
      - liyria.com
    contacts:
      - maya@liyria.com
internal:
  vault_path: internal/meetings
  team_emails:
    - jdknowsthings.com
    - jdbrucecpa.com
    - knowsthings.com
email_overrides:
  personal@gmail.com: alman-partners
  consultant@outlook.com: capital-partners
settings:
  unfiled_path: _unfiled
  duplicate_multi_org: all
  domain_priority: most_attendees
  enable_email_overrides: true
  case_sensitive_emails: false
